apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.ingressgateway.certificate }}
  issuerRef:
    name: default-issuer
  commonName: "*.{{ .Values.ingressgateway.dns  }}"
  dnsNames:
  - "{{ .Values.ingressgateway.dns  }}"
  - "*.{{ .Values.ingressgateway.dns  }}"
