apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: default-issuer
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.server }}
    privateKeySecretRef:
      name: default-issuer
    solvers:
    - dns01:
        cloudDNS:
          project: {{ .Values.project_id }}